console.log(2 + 3);
console.log("a" + "b" + 1);
console.log(1 + "x");
console.log(10 - 4);
console.log(3 * 4);
console.log(10 / 4);
console.log(10 % 3);
console.log(2 ** 8);
console.log(5 & 3);
console.log(5 | 2);
console.log(5 ^ 1);
console.log(1 << 4);
console.log(-8 >> 1);
console.log(-1 >>> 28);
console.log(1 < 2);
console.log("a" < "b");
console.log(1 === 1);
console.log(1 === "1");
console.log(1 == "1");
console.log(null == undefined);
console.log(null === undefined);
console.log(!0);
console.log(!1);
console.log(-5);
console.log(+"5");
console.log(~0);
console.log(typeof 5);
console.log(typeof "s");
console.log(typeof true);
console.log(typeof undefined);
console.log(void 5);
console.log(true ? 1 : 2);
console.log(false ? 1 : 2);
console.log(true && "hit");
console.log(false && "miss");
console.log(false || "hit");
console.log(true || "miss");
console.log(null ?? "hit");
console.log(0 ?? "miss");
