console.log("e");
console.log("");
console.log("");
console.log(104);
console.log(NaN);
console.log("HELLO WORLD");
console.log("hello world");
console.log("ell");
console.log("world");
console.log("hello worl");
console.log("");
console.log("ell");
console.log("ell");
console.log("hello world");
console.log("ababab");
console.log("");
console.log("005");
console.log("500");
console.log("hello");
console.log("xyxyabc");
console.log("hello world!42");
console.log(6);
console.log(-1);
console.log(12);
console.log(true);
console.log(false);
console.log(true);
console.log(false);
console.log(true);
console.log(false);
