console.log("hello".charAt(1));
console.log("hello".charAt(10));
console.log("hello".charAt(-1));
console.log("hello".charCodeAt(0));
console.log("hello".charCodeAt(10));
console.log("Hello World".toUpperCase());
console.log("Hello World".toLowerCase());
console.log("hello world".slice(1, 4));
console.log("hello world".slice(-5));
console.log("hello world".slice(-100, -1));
console.log("hello world".slice(4, 1));
console.log("hello world".substring(1, 4));
console.log("hello world".substring(4, 1));
console.log("hello world".substring(-5, 100));
console.log("ab".repeat(3));
console.log("ab".repeat(0));
console.log("5".padStart(3, "0"));
console.log("5".padEnd(3, "0"));
console.log("hello".padStart(3));
console.log("abc".padStart(7, "xy"));
console.log("hello ".concat("world", "!", 42));
console.log("hello world".indexOf("world"));
console.log("hello world".indexOf("xyz"));
console.log("hello world hello".lastIndexOf("hello"));
console.log("hello world".includes("wor"));
console.log("hello world".includes("xyz"));
console.log("hello world".startsWith("hello"));
console.log("hello world".startsWith("world"));
console.log("hello world".endsWith("world"));
console.log("hello world".endsWith("hello"));
