console.log(Math.PI);
console.log(Math.max(3, 7, -1, 2));
console.log(Math.min(3, 7, -1, 2));
console.log(Math.abs(-5));
console.log(Math.floor(4.7));
console.log(Math.ceil(4.2));
console.log(Math.round(2.5));
console.log(Math.round(-2.5));
console.log(Math.sqrt(16));
console.log(Math.pow(2, 10));
console.log(Math.max());
console.log(Math.min());
console.log(Math.hypot(3, 4));
console.log([1, 2, 3].length);
console.log("hello".length);
console.log([1, 2, 3][1]);
