console.log(Number("42"));
console.log(Number("  3.14  "));
console.log(Number(""));
console.log(Number());
console.log(Number(true));
console.log(Number(false));
console.log(Number(null));
console.log(Number(undefined));
console.log(Number("not a number"));
console.log(String(42));
console.log(String(3.14));
console.log(String());
console.log(String(null));
console.log(String(undefined));
console.log(String(true));
console.log(String(false));
console.log(Boolean(0));
console.log(Boolean(1));
console.log(Boolean(""));
console.log(Boolean("hi"));
console.log(Boolean());
console.log(Boolean(null));
console.log(Boolean(undefined));
console.log(new Number(5));
console.log(new String("x"));
console.log(new Boolean(1));
console.log(typeof Number(5));
console.log(typeof new Number(5));
